[Feature] Build Reusable Widget for Infographics Screen
Western-Health-Covid19-Collaboration/wh_covid19_app pull request #130
Opened 2020-03-29 12:40 UTC by yimingc2

## Abstract
This PR will create a reusable infographics page with a zoomable image. This page will be used in multiple places.

- [x] `release-notes.txt` has been updated.

## Changes

- Add photo_view dependency
- Add configurable (image, color and title) infographics page for reuse
- Use different share icons based on platform (Android/iOS)
- Apply close (X) icon to left navigation bar button

## Screenshots
![zoom](https://user-images.githubusercontent.com/14011195/77849091-c8ae4d00-7214-11ea-94af-6d5892ae28a2.gif)

## Things to note
- Not sure what infographic image should be used so I put Intubation Checklist Image for now
- The reusable infographics page has been applied to the Algorithm page for now. The route will be changed in #112

2020-03-30 22:00 UTC, maks requested changes
:tada: excellent work @yimingc2 ! Just a few small issues to address.

2020-03-30 22:00 UTC, maks commented on lib/view/reusable_infographic_page.dart
> +          IconButton(
could we please break this out into a separate "platform icon button" widget, which takes a named const that represents the required icon, the constant can then be a map, with each asset path keyed by platform name

2020-03-30 22:00 UTC, maks commented on lib/widget/reusable_zoomable_widget.dart
> +                  customSize: Size(MediaQuery.of(context).size.width - margin * 2, MediaQuery.of(context).size.height - margin * 2),
could we break this calc into a separate function that returns the `Size` for clarity?

2020-03-31 10:33 UTC, yimingc2 commented on lib/view/reusable_infographic_page.dart
> +          IconButton(
Do you mean create a general reusable platform icon button or just the button for sharing? If it's first one, then we will need to pass the action as well.

2020-04-01 10:08 UTC, maks approved these changes
:+1: :100:

2020-04-01 10:10 UTC, merged