Fill out intubation guidance screen, resolves #37
Western-Health-Covid19-Collaboration/wh_covid19_app pull request #133
Opened 2020-03-30 13:45 UTC by rockgecko-development

Intubation guidance screen

6 pages of intubation guidance, in horizontally swipeable tab form.

## Changes

- `models\intubation_guide.dart` has simple reusable data structure consisting of a section title, then list of sections containing icon, title and subtitle. This structure could easily be converted to json in the future if necessary.
-`view_templates\intubation_content_view_template.dart` Renders a IntubationContent screen.
-These could both be easily reused if there are other similar screens.

## Screenshots
![image](https://user-images.githubusercontent.com/15306325/77918653-e993a280-72e7-11ea-97a9-b5b7a964faad.png)

## Things to note

I used a different emoji for "Minimise apnoea time while minimising risk of cough ⚖️" because 🤏 was only added to unicode last year. Instead, I moved the scales ⚖️ from the title to the leading icon ⚖ . See screenshot.

2020-03-30 22:14 UTC, maks requested changes
:tada: :100: excellent work @rockgecko-development  jut a couple of minor nits

2020-03-30 22:14 UTC, maks commented on lib/view/intubation/guidance/intubation_guidance_page.dart
> +            unselectedLabelColor: AppColors.blackAlpha800.withOpacity(0.32),
maybe add this colour to AppColors as new const ?

2020-03-30 22:14 UTC, maks commented on lib/view/view_templates/intubation_content_view_template.dart
> +            throw 'Invalid IntubationContent item type $item';
throw an Error or Exception not just string pls

2020-03-30 23:16 UTC, kimngyn commented on lib/hard_data.dart
> +          'Attached to manual ventilation device or Anaesthetic machine',
```suggestion
          'Avoid manual bagging unless rescue oxygenation',
```

2020-03-30 23:16 UTC, kimngyn commented on lib/hard_data.dart
> +      IntubationItem('Minimise apnoea time while minimising risk of cough',
missing another icon? 🤏

2020-03-31 00:12 UTC, rockgecko-development commented on lib/hard_data.dart
> +          'Attached to manual ventilation device or Anaesthetic machine',
Thanks, good pickup!

2020-03-31 09:04 UTC, maks approved these changes
:+1: Great stuff @rockgecko-development  Please just make sure you run `flutter clean && fluter analyze` to make sure you spot any lint issues.

2020-03-31 09:37 UTC, rockgecko-development commented
I literally don't understand what the problem is here. Output is:
> info • Only use double quotes for strings containing single quotes • lib/hard_data.dart:266:22 • prefer_single_quotes
The string _does_ contain quotes??
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/4935ed74df7e9b2da65c14317c941281886f5262/lib/hard_data.dart#L266

2020-03-31 09:55 UTC, maks commented
@rockgecko-development PLEASE run `flutter clean && flutter analyze` BEFORE pushing to the PR branch as otherwise we're burning thru a lot of CI minutes :disappointed:

2020-03-31 09:56 UTC, maks commented
@rockgecko-development https://codemagic.io/app/5e75f4bfdd1d6d000a198e90/build/5e830f9229657a000d4a9876

2020-03-31 10:02 UTC, merged