Feat/issue 38 intubations checklist
Western-Health-Covid19-Collaboration/wh_covid19_app pull request #137
Opened 2020-03-30 23:37 UTC by ericjiang97

☝️ Provide a short & descriptive title for this PR.

Provide a more detailed summary of the changes in this PR here.  What does it do?

- [x] `release-notes.txt` has been updated.
(👆 delete this line if your changes have no user facing features)

## Changes

- Initial work on the Checklist ✅ 
- Added reusable checkbox component 🔧 
- Added more models for future proofing.

## Screenshots

https://ejiang.d.pr/piupi4

## Things to note

2020-03-31 07:17 UTC, rockgecko-development approved these changes
[duplicate msg]

2020-03-31 07:17 UTC, rockgecko-development commented on lib/view/intubation/checklist/intubation_checklist_page.dart
> +            labelColor: AppColors.blackAlpha800,
The tab bar indicator style should be bold according to mocks. I used the following to style the tab bar in intubation guidance #133:
```
labelColor: AppColors.blackAlpha800,
labelStyle: AppStyles.textSemiBold,
unselectedLabelColor: AppColors.tabBarDeselectedText,
indicatorColor: AppColors.green900,
```
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/464be6825dab06fcb3a259ffb256f78aea9fc9cc/lib/view/intubation/guidance/intubation_guidance_page.dart#L21

2020-03-31 07:19 UTC, rockgecko-development requested changes
Looks great! One minor thing re tab bar design

2020-03-31 07:19 UTC, rockgecko-development commented on lib/view/intubation/checklist/intubation_checklist_page.dart
> +            unselectedLabelColor: AppColors.grey600,
The tab bar indicator style should be bold according to mocks. I used the following to style the tab bar in intubation guidance #133:
```
labelColor: AppColors.blackAlpha800,
labelStyle: AppStyles.textSemiBold,
unselectedLabelColor: AppColors.tabBarDeselectedText,
indicatorColor: AppColors.green900,
```
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/464be6825dab06fcb3a259ffb256f78aea9fc9cc/lib/view/intubation/guidance/intubation_guidance_page.dart#L21

2020-04-01 01:43 UTC, kimngyn commented on lib/hard_data.dart
> +      title: 'IV access x 2',
```suggestion
      title: 'IV access x 2', notes: ['1L fluid on pump set']
```

2020-04-01 05:27 UTC, kimngyn commented on lib/hard_data.dart
> +      title: 'Fluid runs easily',
```suggestion
      title: 'Fluid runs easily'
```

2020-04-01 08:44 UTC, rockgecko-development commented
Hi @ericjiang97 , i think you missed  my comment. Necessary if we want the tab bar appearance to match checklist vs intubation guide pages 

https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/6c88ce261f669d284de723d6e5617bb07f2cc730/lib/view/intubation/guidance/intubation_guidance_page.dart#L20

2020-04-01 08:56 UTC, rockgecko-development approved these changes

2020-04-01 08:57 UTC, merged