Fix for issue180 - Disclaimer text
Western-Health-Covid19-Collaboration/wh_covid19_app pull request #191
Opened 2020-04-05 10:45 UTC by lukesleeman

Some minor changes to the disclaimer text.  Closes #180 

- [x] `release-notes.txt` has been updated.

## Changes

- Fix capitalisation
- Remove repeated "have"

## Screenshots

![image](https://user-images.githubusercontent.com/902252/78472695-4080f800-777e-11ea-9736-9fefbdaff4b2.png)

## Things to note

I've bumped up the disclaimer to V2 - should be a good test to ensure everybody needs to re-accept it.

2020-04-05 23:34 UTC, kimngyn requested changes

2020-04-05 23:34 UTC, kimngyn commented on lib/strings.dart
> +This app is designed to be used by anaesthetic and critical care doctors at Western Health who are caring for patients during the COVID-19 Pandemic. The guidelines, protocols and advice within this a
```suggestion
This app is designed to be used by the anaesthetist and critical care doctors at Western Health who are caring for patients during the COVID-19 pandemic. The guidelines, protocols and advice within this app are designed to educate staff and suggest recommended management of patients with COVID-19. The recommendations within this application do not indicate an exclusive course of action as the results must be contextualised to the patient at hand and variations may be appropriate.
```

2020-04-05 23:34 UTC, kimngyn commented on lib/view/disclaimer_view.dart
> +                            'This app is for clinician and hospital staff use ONLY\n',
Good!

2020-04-06 09:58 UTC, kimngyn commented on lib/view/disclaimer_view.dart
> +                            'This app is for clinician and hospital staff use ONLY\n',
```suggestion
                            'This app is for clinicians and hospital staff use ONLY\n',
```

2020-04-06 22:29 UTC, workerbee22 approved these changes
LGTM

2020-04-06 22:34 UTC, workerbee22 commented
@luke good idea taking to version 2.

2020-04-06 22:41 UTC, workerbee22 commented
@kimngyn I also spotted a bug with Disclaimer back button on the app bar https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/195 which you may or may not want to fix as part of this PR? If you have questions about the themes just msg me.

2020-04-07 09:36 UTC, merged